"""empty message

Revision ID: 6e15432efa2c
Revises: 0786c0a0a332
Create Date: 2023-07-20 14:27:47.853723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e15432efa2c'
down_revision = '0786c0a0a332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_post_like_post_id_post')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_like_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_like'))
    )
    op.drop_table('like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('likes_post', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['likes_post'], ['users.id'], name='fk_like_likes_post_users'),
    sa.PrimaryKeyConstraint('id', name='pk_like')
    )
    op.drop_table('post_like')
    # ### end Alembic commands ###
