"""empty message

Revision ID: a09beecfcd66
Revises: 2a9a799c0916
Create Date: 2023-07-20 14:47:16.596421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09beecfcd66'
down_revision = '2a9a799c0916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_post_like_post_id_post')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_like_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_like'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_like')
    # ### end Alembic commands ###
