"""empty message

Revision ID: c05ddfa71c73
Revises: 107b8965c3b6
Create Date: 2023-07-20 12:13:54.067608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05ddfa71c73'
down_revision = '107b8965c3b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_post_like_users'), 'users', ['like'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_post_like_users'), type_='foreignkey')
        batch_op.drop_column('like')

    # ### end Alembic commands ###
